### ISSUE TITLE
Health Check stuck "Results are still loading…"; Uncaught TypeError in JS console

### ISSUE THREAD

**Issue by paulschreiber** [WordPress/health-check#379] opened 2020-05-10 04:23 UTC
### Feature request/bug description

On some sites, Health Check gets stuck at the "Results are still loading…" screen and never finishes.

![image](https://user-images.githubusercontent.com/86784/81490738-aa942d80-9253-11ea-8abf-f8627323a762.png)

The following error appears in the JavaScript console immediately:
```
VM439:9 Uncaught TypeError: Cannot read property 'color' of undefined
    at eval (eval at v.template (load-scripts.php?c=0&load[chunk_0]=hoverIntent,common,hoverintent-js,admin-bar,thickbox,clipboard,underscore,wp-util&ver=5.4.1:352), <anonymous>:9:20)
    at u (load-scripts.php?c=0&load[chunk_0]=hoverIntent,common,hoverintent-js,admin-bar,thickbox,clipboard,underscore,wp-util&ver=5.4.1:352)
    at load-scripts.php?c=0&load[chunk_0]=hoverIntent,common,hoverintent-js,admin-bar,thickbox,clipboard,underscore,wp-util&ver=5.4.1:354
    at l (site-health.min.js?ver=5.4.1:2)
    at site-health.min.js?ver=5.4.1:2
    at Function.each (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:2)
    at HTMLDocument.<anonymous> (site-health.min.js?ver=5.4.1:2)
    at i (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:2)
    at Function.ready (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:2)
```

After 70 seconds, the following AJAX call is made:
```
/wp-admin/admin-ajax.php?_fs_blog_admin=true
```

with this response:
```
{"wp-auth-check":true,"server_time":1589084388}
```

and this JS stack trace:
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined
    at HTMLDocument.<anonymous> (wp-auth-check.min.js?ver=5.4.1:2)
    at HTMLDocument.dispatch (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:3)
    at HTMLDocument.r.handle (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:3)
    at Object.trigger (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:3)
    at Object.a.event.trigger (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:8)
    at HTMLDocument.<anonymous> (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:3)
    at Function.each (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:2)
    at a.fn.init.each (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:2)
    at a.fn.init.trigger (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-progressbar&ver=5.4.1:3)
    at Object.<anonymous> (heartbeat.min.js?ver=5.4.1:2)
```

### Config
WordPress 5.4.1
Site Health 1.4
PHP 7.4.5
Apache 2.4.41 (Ubuntu)

### Reproducibility
This reproduces 100% of the time on some sites, 0% on some other sites on the same server.

**Comment by Clorith** [comment] 2020-05-19 20:58
It sounds like you might be running Jetpack or similar on some sites? They've got a bug in their release which prevents the Site Health component from finishing like it should.

We're looking at ways to harden this so that plugins are less likely to break it in the future.

Would be great if you could confirm that Jetpack is present on the sites where the problem is occurring though.

**Comment by paulschreiber** [comment] 2020-05-19 21:19
Confirmed that sites with Jetpack 8.5 are experiencing this problem.

**Comment by jpfeuffer** [comment] 2020-10-08 21:46
We have the same problem with the same error and do not have JetPack installed.

```
Uncaught TypeError: Cannot read property 'hasClass' of undefined
https://www.openms.de/wp-includes/js/wp-auth-check.min.js?ver=5.5.1 line 2
```

Is this about the REST API? We have API Bearer Auth installed.

**Comment by jpfeuffer** [comment] 2020-10-08 21:50
We have the same problem with the same error and do not have JetPack installed.

```
Uncaught TypeError: Cannot read property 'hasClass' of undefined
/wp-includes/js/wp-auth-check.min.js?ver=5.5.1 line 2
```

Is this about the REST API? We have API Bearer Auth installed.

**Comment by Clorith** [comment] 2022-09-10 16:04
I'm closing this issue, as it was related to a compatibility issue.

The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating ot these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org).

**Closed as completed by Clorith** 2022-09-10 16:04 UTC
