### ISSUE TITLE
Default Theme not up to date

### ISSUE THREAD

**Issue by knutsp** [WordPress/health-check#366] opened 2019-12-20 16:47 UTC
### Bug description

When going to troubleshooting mode without Twenty Nineteen, with Twenty Twenty, it complains that no default theme is installed and offers to install one, which comes up as Twenty Nineteen.

Isn't it a WP constant saying which is the default theme? Is this hard coded in this plugin? Should be fixed and kept up to date, as it's annoying to have to install Twenty Nineteen again to get full troubleshooting.

**Comment by Clorith** [comment] 2020-01-06 21:02
This is partially by design, when offering support it's generally not recommend to use the latest default theme until a few months after its release (as history shows that new default themes often need a few patches after release before it becomes stable and reliable for troubleshooting purposes).

The theme should be updated with the next major release of the plugin though, I'll milestone it for visibility.

**Comment by knutsp** [comment] 2020-01-08 09:35
Then the plugin should accept both (last, previous) in case last is too new, as a default theme for the purpose of fallback. Maybe more of them, like last three or four.

But, isn't the only real fallback WP will actually use set in the WP_DEFAULT_THEME constant? Or is this plugin overriding it?

**Comment by Clorith** [comment] 2020-01-11 12:20
The fallback is in the `WP_DEFAULT_THEME`, yes, but Troubleshooting Mode is separate from this and relies on a hardcoded list of recommendations; https://github.com/WordPress/health-check/blob/3fee540621879cacac3e14dcc486ce606d24861a/src/assets/mu-plugin/health-check-troubleshooting-mode.php#L34-L44

Troubleshooting Mode doesn't care about the fallback though, it is interested in resolving issues, which is why this differs for a while after a new theme is released.

**Comment by Clorith** [comment] 2020-03-30 00:29
This was added in 35939b04c1522e0afa0b6250a5427c0dd538ecd8 and will be included in the next plugin release.

**Closed as completed by Clorith** 2020-03-30 00:29 UTC
